name: 'e2e test'

on:
  workflow_call:
    secrets:
      HW_OBS_AK:
        required: true  # Â£∞ÊòéËØ•ÂØÜÈí•‰∏∫ÂøÖÂ°´
        description: "Huawei OBS Access Key"
      HW_OBS_SK:
        required: true
        description: "Huawei OBS Secret Key"
    inputs:
      vllm:
        required: true
        type: string
      runner:
        required: true
        type: string
      image:
        required: true
        type: string
      type:
        required: true
        type: string
      contains_310:
        required: true
        type: boolean

jobs:
  e2e-light:
    name: singlecard-light
    runs-on: linux-arm64-npu-1
    strategy:
      fail-fast: false
      matrix:
        part: [0]
    container:
      image: ${{ inputs.image }}
      env:
        VLLM_LOGGING_LEVEL: ERROR
        VLLM_USE_MODELSCOPE: True
        HF_HUB_OFFLINE: 1
        # Additional sccache optimizations
        SCCACHE_MAX_FRAME_LENGTH: 104857600
        SCCACHE_IDLE_TIMEOUT: 0
        # SCCACHE ÈÖçÁΩÆÔºö‰ΩøÁî®ÂÖ±‰∫´Áõò
        SCCACHE_BUCKET: obs-guiiyang1-ascend-test
        SCCACHE_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
        AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
        AWS_S3_FORCE_PATH_STYLE: true
        SCCACHE_REGION: cn-southwest-2
        SCCACHE_S3_ENABLE_VIRTUAL_HOST_STYLE: true
        #SCCACHE_REDIS: redis://10.0.0.98:6379
        #SCCACHE_LOG: debug
        SCCACHE_SLOPPINESS: time_macros,include_file_mtime,file_stat_matches,path_prefix_replacement
        #SCCACHE_DIRECT: true
        #SCCACHE_IGNORE_SERVER_IO_ERROR: 1
        #SCCACHE_COMPILER_WRAPPER: 1
        #SCCACHE_CACHE_SIZE: 50G
        # uv ÈÖçÁΩÆ
        UV_INDEX_URL: http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple
        UV_EXTRA_INDEX_URL: https://mirrors.huaweicloud.com/ascend/repos/pypi
        UV_INDEX_STRATEGY: unsafe-best-match
        UV_NO_CACHE: 1
        #UV_CACHE_DIR: /tmp/uv_cache
        #UV_LINK_MODE: symlink

        #CCACHE_DIR: /tmp/ccache
        #CCACHE_MAXSIZE: 20G
        #CCACHE_SLOPPINESS: time_macros,include_file_mtime,include_file_ctime
        #CCACHE_COMPRESS: true
        #CCACHE_COMPRESSLEVEL: 6
        #CCACHE_NOHASHDIR: true
    steps:
      - name: Checkout vllm-project/vllm-ascend repo
        uses: actions/checkout@v6
      - name: Checkout vllm-project/vllm repo
        uses: actions/checkout@v6
        with:
          repository: vllm-project/vllm
          ref: ${{ inputs.vllm }}
          path: ./vllm-empty
          fetch-depth: 1
      - name: Config mirrors
        run: |
          sed -Ei 's@(ports|archive).ubuntu.com@cache-service.nginx-pypi-cache.svc.cluster.local:8081@g' /etc/apt/sources.list
          pip config set global.index-url http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple
          pip config set global.trusted-host cache-service.nginx-pypi-cache.svc.cluster.local
          apt-get update -y
          apt install git -y
      - name: disable apt clean
        run: |
          rm -f /etc/apt/apt.conf.d/docker-clean
      - name: Check npu and CANN info
        run: |
          npu-smi info
          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
          ls -la packages.txt || echo "packages.txt NOT FOUND"
          ls -la .github/workflows/_e2e_test.yaml || echo "_e2e_test.yaml NOT FOUND"
          echo "Hash is: ${{ hashFiles('./packages.txt') }}"
#      - name: Cache dependencies
#        uses: runs-on/cache@v4
#        with:
#          path: |
#            /tmp/uv_cache
#          key: ascend-${{ runner.os }}-pip-vllm-v1-${{ hashFiles('**/requirements-dev.txt', './vllm-empty/pyproject.toml', './vllm-empty/requirements/**/*.txt') }}
#          restore-keys: |
#            ascend-${{ runner.os }}-pip-vllm-v1
#        env:
#          # üëá ÊåáÂÆö‰Ω†ÁöÑ OBS bucketÔºàÂøÖÈ°ªÁî® virtual-hosted ÂüüÂêçÔºÅÔºâ
#          RUNS_ON_S3_BUCKET_CACHE: obs-guiiyang1-ascend-test
#          RUNS_ON_S3_BUCKET_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
#          AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
#          AWS_REGION: cn-southwest-2
#      - name: Cache dependencies
#        uses: runs-on/cache@v4
#        with:
#          path: |
#            /tmp/ccache
#          key: ascend-${{ runner.os }}-ccache-vllm-v1-${{ hashFiles('**/requirements-dev.txt', './vllm-empty/pyproject.toml', './vllm-empty/requirements/**/*.txt') }}
#          restore-keys: |
#            ascend-${{ runner.os }}-ccache-vllm-v1
#        env:
#          # üëá ÊåáÂÆö‰Ω†ÁöÑ OBS bucketÔºàÂøÖÈ°ªÁî® virtual-hosted ÂüüÂêçÔºÅÔºâ
#          RUNS_ON_S3_BUCKET_CACHE: obs-guiiyang1-ascend-test
#          RUNS_ON_S3_BUCKET_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
#          AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
#          AWS_REGION: cn-southwest-2

      - name: Install uv (if not pre-installed)
        run: |
          pip install uv
          uv pip index  versions sccache
          uv pip install --system sccache
          sccache --start-server
          #sccache --show-stats
#          UV_VERSION="0.9.30"
#          FILENAME="uv-${UV_VERSION}-aarch64-unknown-linux-musl.tar.gz"
#          DOWNLOAD_FILENAME="uv-aarch64-unknown-linux-musl.tar.gz"
#          CACHE_DIR="/shared-data/uv"
#          if [ -f "$CACHE_DIR/$FILENAME" ]; then
#            echo "Found cached uv package successfully"
#          else
#            echo "uv package not found in cache. Downloading..."
#            mkdir -p "$CACHE_DIR"
#            apt update && apt install -y curl
#            curl --connect-timeout 30 --retry 3 -L "https://github.com/astral-sh/uv/releases/download/${UV_VERSION}/uv-aarch64-unknown-linux-musl.tar.gz" -o "$CACHE_DIR/$DOWNLOAD_FILENAME"
#            mv "$CACHE_DIR/$DOWNLOAD_FILENAME" "$CACHE_DIR/$FILENAME"
#          fi
#          mkdir -p /tmp/uv
#          tar -xzf "$CACHE_DIR/$FILENAME" -C /tmp/uv
#          mv /tmp/uv/uv-aarch64-unknown-linux-musl/uv /usr/local/bin/
#          chmod +x /usr/local/bin/uv
#          echo "=== uv version ==="
#          uv --version
#          echo "=== uv configuration ==="
#          uv cache dir

      - name: Install system dependencies
        run: |
          start_time=$(date +%s)
          apt-get -y install `cat packages.txt`
          apt-get -y install gcc g++ cmake libnuma-dev clang-15
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "==========apt installÊÄªËÄóÊó∂Ôºö$duration ÁßíÔºà$((duration/60)) ÂàÜ $((duration%60)) ÁßíÔºâ"
          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 20
          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 20
          #sleep 600

      - name: Install vllm-project/vllm from source
        working-directory: ./vllm-empty
        run: |
          uv pip install --system --no-build-isolation uc-manager
          VLLM_TARGET_DEVICE=empty uv pip install --system -e .

      - name: Install vllm-project/vllm-ascend
        env:
          PIP_EXTRA_INDEX_URL: https://mirrors.huaweicloud.com/ascend/repos/pypi
          # ÁºñËØëÂô®ÂåÖË£ÖÂô®ÈÖçÁΩÆ
          # Set SOURCE_DATE_EPOCH for reproducible builds
          SOURCE_DATE_EPOCH: 1
        run: |
          start_time=$(date +%s)
          pip install uc-manager
          end_time0=$(date +%s)
          duration=$((end_time0 - start_time))
          echo "==========install uc-managerÊÄªËÄóÊó∂Ôºö$duration ÁßíÔºà$((duration/60)) ÂàÜ $((duration%60)) ÁßíÔºâ"
          uv pip install --system -r requirements-dev.txt
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "==========install requirementsÊÄªËÄóÊó∂Ôºö$duration ÁßíÔºà$((duration/60)) ÂàÜ $((duration%60)) ÁßíÔºâ"
          uv pip install --system --no-build-isolation -v -e .
          #sccache --show-stats
          end_time1=$(date +%s)
          duration=$((end_time1 - end_time))
          echo "==========buildÊÄªËÄóÊó∂Ôºö$duration ÁßíÔºà$((duration/60)) ÂàÜ $((duration%60)) ÁßíÔºâ"
          sccache -s
          #sleep 6000
#      - name: Run vllm-project/vllm-ascend test
#        env:
#          PYTORCH_NPU_ALLOC_CONF: max_split_size_mb:256
#          VLLM_WORKER_MULTIPROC_METHOD: spawn
#        run: |
#          python3 .github/workflows/scripts/run_suite.py --suite e2e-singlecard-light --auto-partition-id ${{ matrix.part }} --auto-partition-size 1