name: 'e2e test'

on:
  workflow_call:
    secrets:
      HW_OBS_AK:
        required: true  # å£°æ˜è¯¥å¯†é’¥ä¸ºå¿…å¡«
        description: "Huawei OBS Access Key"
      HW_OBS_SK:
        required: true
        description: "Huawei OBS Secret Key"
      HW_REDIS_PWD:
        required: true
        description: "Huawei redis password"
    inputs:
      vllm:
        required: true
        type: string
      runner:
        required: true
        type: string
      image:
        required: true
        type: string
      type:
        required: true
        type: string
      contains_310:
        required: true
        type: boolean
env:
  UV_INDEX_URL: http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple
  UV_EXTRA_INDEX_URL: https://mirrors.huaweicloud.com/ascend/repos/pypi
  UV_INDEX_STRATEGY: unsafe-best-match
  UV_NO_CACHE: 1
  UV_PYTHON_DOWNLOADS: never
  UV_SYSTEM_PYTHON: 1

  AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
  SCCACHE_BUCKET: obs-guiiyang1-ascend-test
  SCCACHE_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
  #SCCACHE_REGION: cn-southwest-2
  SCCACHE_S3_ENABLE_VIRTUAL_HOST_STYLE: true

jobs:
  e2e-light:
    name: singlecard-light
    runs-on: linux-arm64-npu-1
    strategy:
      fail-fast: false
      matrix:
        part: [0]
    container:
      image: ${{ inputs.image }}
      env:
        VLLM_LOGGING_LEVEL: ERROR
        VLLM_USE_MODELSCOPE: True
        HF_HUB_OFFLINE: 1
    steps:
      - name: Checkout vllm-project/vllm-ascend repo
        uses: actions/checkout@v6
      - name: Checkout vllm-project/vllm repo
        uses: actions/checkout@v6
        with:
          repository: vllm-project/vllm
          ref: ${{ inputs.vllm }}
          path: ./vllm-empty
          fetch-depth: 1
      - name: Config mirrors
        run: |
          sed -Ei 's@(ports|archive).ubuntu.com@cache-service.nginx-pypi-cache.svc.cluster.local:8081@g' /etc/apt/sources.list
          pip config set global.index-url http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple
          pip config set global.trusted-host cache-service.nginx-pypi-cache.svc.cluster.local
          apt-get update -y
          apt install git -y
          pip install uv
          uv venv
          uv pip install --system sccache
          sccache -s

      - name: Check npu and CANN info
        run: |
          npu-smi info
          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
          DIR_HASH=$(find ./csrc -type f -not -path '*/.*' | sort | xargs sha256sum | sha256sum | awk '{print $1}')
          echo "DIR_HASH=$DIR_HASH" >> $GITHUB_OUTPUT
      - name: get hash
        id: get_dir_hash
        run: |
          DIR_HASH=$(find ./csrc -type f -not -path '*/.*' | sort | xargs sha256sum | sha256sum | awk '{print $1}')
          echo "DIR_HASH=$DIR_HASH" >> $GITHUB_OUTPUT
          echo "hash: $DIR_HASH"
      - name: Cache dependencies
        uses: runs-on/cache@v4
        with:
          path: |
            /tmp/uv_cache
          key: ascend-${{ runner.os }}-pip-vllm-v1-${{ steps.get_dir_hash.outputs.DIR_HASH }}
          restore-keys: |
            ascend-${{ runner.os }}-pip-vllm-v1-${{ steps.get_dir_hash.outputs.DIR_HASH }}
        env:
          # ğŸ‘‡ æŒ‡å®šä½ çš„ OBS bucketï¼ˆå¿…é¡»ç”¨ virtual-hosted åŸŸåï¼ï¼‰
          RUNS_ON_S3_BUCKET_CACHE: obs-guiiyang1-ascend-test
          RUNS_ON_S3_BUCKET_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
          AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
          AWS_REGION: cn-southwest-2
#      - name: Cache dependencies
#        uses: runs-on/cache@v4
#        with:
#          path: |
#            /tmp/ccache
#          key: ascend-${{ runner.os }}-ccache-vllm-v1-${{ hashFiles('**/requirements-dev.txt', './vllm-empty/pyproject.toml', './vllm-empty/requirements/**/*.txt') }}
#          restore-keys: |
#            ascend-${{ runner.os }}-ccache-vllm-v1
#        env:
#          # ğŸ‘‡ æŒ‡å®šä½ çš„ OBS bucketï¼ˆå¿…é¡»ç”¨ virtual-hosted åŸŸåï¼ï¼‰
#          RUNS_ON_S3_BUCKET_CACHE: obs-guiiyang1-ascend-test
#          RUNS_ON_S3_BUCKET_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
#          AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
#          AWS_REGION: cn-southwest-2

#      - name: Install sccache (if not pre-installed)
#        run: |
#          FILENAME="sccache-v0.13.0-aarch64-unknown-linux-musl.tar.gz"
#          CACHE_DIR="/shared-data/sccache"
#          if [ -f "$CACHE_DIR/$FILENAME" ]; then
#            echo "Found cached sccache package successfully"
#          else
#            echo "sccache package not found in cache. Downloading..."
#            mkdir -p "$CACHE_DIR"
#            apt update && apt install -y curl
#            curl --connect-timeout 30 --retry 3 -L https://github.com/mozilla/sccache/releases/download/v0.13.0/sccache-v0.13.0-aarch64-unknown-linux-musl.tar.gz -o "$CACHE_DIR/$FILENAME"
#          fi
#          mkdir -p /tmp/sccache
#          tar -xzf "$CACHE_DIR/$FILENAME" -C /tmp/sccache
#          mv /tmp/sccache/sccache-v0.13.0-aarch64-unknown-linux-musl/sccache /usr/local/bin/
#          chmod +x /usr/local/bin/sccache
#          sccache --start-server
#          sccache --show-stats

#      - name: Install system dependencies
#        run: |
#          start_time=$(date +%s)
#          apt-get -y install `cat packages.txt`
#          apt-get -y install gcc g++ cmake libnuma-dev clang-15
#          end_time=$(date +%s)
#          duration=$((end_time - start_time))
#          echo "==========apt installæ€»è€—æ—¶ï¼š$duration ç§’ï¼ˆ$((duration/60)) åˆ† $((duration%60)) ç§’ï¼‰"
#          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 20
#          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 20
#          #sleep 600
      - name: Install vllm-project/vllm from source
        working-directory: ./vllm-empty
        run: |
          VLLM_TARGET_DEVICE=empty uv pip install -e .

      - name: Install vllm-project/vllm-ascend
        env:
          PIP_EXTRA_INDEX_URL: https://mirrors.huaweicloud.com/ascend/repos/pypi
          # ç¼–è¯‘å™¨åŒ…è£…å™¨é…ç½®
          # Set SOURCE_DATE_EPOCH for reproducible builds
          SOURCE_DATE_EPOCH: 1
        run: |
          start_time=$(date +%s)
          pip install uc-manager
          end_time0=$(date +%s)
          duration=$((end_time0 - start_time))
          echo "==========install uc-manageræ€»è€—æ—¶ï¼š$duration ç§’ï¼ˆ$((duration/60)) åˆ† $((duration%60)) ç§’ï¼‰"
          uv pip install -r requirements-dev.txt
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "==========install requirementsæ€»è€—æ—¶ï¼š$duration ç§’ï¼ˆ$((duration/60)) åˆ† $((duration%60)) ç§’ï¼‰"
          uv pip install --no-build-isolation -v -e .
          #sccache --show-stats
          end_time1=$(date +%s)
          duration=$((end_time1 - end_time))
          echo "==========buildæ€»è€—æ—¶ï¼š$duration ç§’ï¼ˆ$((duration/60)) åˆ† $((duration%60)) ç§’ï¼‰"
          sccache -s
          #sleep 6000
